[constants]
c = c
mu0 = mu_0
m_e = m_e
eps0 = epsilon_0
qe = e

[freq_feature.94GHz]
name = "94GHz Interferometer"
freq = 94.0e9
n_ch = 5
; Number of passes through the plasma
n_path = 2

[freq_feature.280GHz]
name = "280GHz Interferometer"
freq = 282.0e9
n_ch = 1
; Number of passes through the plasma
n_path = 1

[channel_assign.01_cdm_280_all]
shot_min = 41542
filename_contains = _ALL
profile = freq_feature.280GHz
method = CDM
ref_col = CH0
probe_cols = ["CH1"]

[channel_assign.02_cdm_94_ref]
shot_min = 41542
filename_regex = _0
profile = freq_feature.94GHz
method = CDM
ref_col = CH0
probe_cols = ["CH1", "CH2"]

[channel_assign.03_cdm_94_shared]
shot_min = 41542
profile = freq_feature.94GHz
method = CDM
ref_col =
probe_cols = ["CH0", "CH1", "CH2"]

[channel_assign.04_fpga_94]
shot_min = 39302
shot_max = 41398
profile = freq_feature.94GHz
method = FPGA
ref_col = CH0
probe_cols = ["CH1", "CH2", "CH3", "CH4", "CH5"]
amp_ref_col = CH16
amp_probe_cols = ["CH17", "CH18", "CH19", "CH20", "CH21"]

[channel_assign.05_iq_94]
shot_min = 30000
shot_max = 39265
profile = freq_feature.94GHz
method = IQ
ref_col = None
probe_cols = [("CH0", "CH1")]

[channel_assign.99_unknown]
profile = freq_feature.94GHz
method = unknown
ref_col = None
probe_cols = []
