#!/usr/bin/env python3
"""
HDF5 I/O Utilities
==================

This module contains the functions for HDF5 I/O utilities.
It includes the functions for HDF5 structure naming/sanitization and metadata attrs helpers.

Author: J. Wang
Date: 2025-01-16
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any, Mapping  # noqa: UP035

import numpy as np

from .log_manager import LogManager

logger = LogManager().get_logger(__name__, "WARNING")

# Canonical top-level groups
H5_GROUP_RAWDATA = "rawdata"
H5_GROUP_DENSITY = "density"
H5_GROUP_STFT = "stft"
H5_GROUP_CWT = "cwt"
H5_GROUP_VEST = "vestdata"

# Metadata key shaping
H5_META_SEP = "__"

NATURAL_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def h5_safe_token(name: str) -> str:
    """Make a token safe for HDF5 naming without enforcing a leading alpha."""
    if not name:
        return name
    safe = str(name).replace(".", "_").replace("/", "_").replace("\\", "_")
    return re.sub(r"[^a-zA-Z0-9_]", "_", safe)


def h5_safe_name(name: str) -> str:
    """Make a name safe for HDF5/PyTables natural naming."""
    if not name:
        return name
    safe = h5_safe_token(name)
    if safe[0].isdigit():
        safe = "data_" + safe
    return safe


def h5_affixed_name(
    stem: str | float | int,
    *,
    prefix: str | None = None,
    suffix: str | None = None,
    prefix_sep: str = "_",
    suffix_sep: str = "_",
) -> str:
    """Build a safe name from a stem with optional safe prefix/suffix."""
    if prefix is None and suffix is None:
        return h5_safe_name(str(stem))
    name = h5_safe_token(str(stem))
    if prefix:
        name = f"{h5_safe_token(prefix)}{prefix_sep}{name}"
    if suffix:
        name = f"{name}{suffix_sep}{h5_safe_token(suffix)}"
    return name


def parse_h5_affixed_name(
    name: str,
    *,
    prefix: str | None = None,
    suffix: str | None = None,
    prefix_sep: str = "_",
    suffix_sep: str = "_",
) -> str | None:
    """Parse a safe name generated by `h5_affixed_name` and recover the stem."""
    text = str(name)
    if prefix:
        prefix_text = f"{h5_safe_name(prefix)}{prefix_sep}"
        if not text.startswith(prefix_text):
            return None
        text = text[len(prefix_text) :]
    if suffix:
        suffix_text = f"{suffix_sep}{h5_safe_name(suffix)}"
        if not text.endswith(suffix_text):
            return None
        text = text[: -len(suffix_text)]
    return text or None


def ensure_unique_name(candidate: str, used_names: set[str]) -> str:
    """Ensure an object name is unique within the current HDF5 group."""
    if candidate not in used_names:
        used_names.add(candidate)
        return candidate

    idx = 1
    while f"{candidate}_{idx:03d}" in used_names:
        idx += 1
    unique_name = f"{candidate}_{idx:03d}"
    used_names.add(unique_name)
    return unique_name


def normalize_source_name(name: str) -> str:
    """
    Normalize a source identifier to a stable display name.

    If a path-like string is given, this returns the basename so that
    `Z:\\...\\a.csv` and `\\\\ip\\...\\a.csv` map to the same logical name.
    """
    text = str(name)
    if "\\" in text or "/" in text:
        #TODO: will be monitored whether this function is followed by `h5_safe_name`
        return Path(text).name  # return Path(text).stem
    return text


def make_h5_group_name(
    original_name: str,
    prefix: str,
    used_names: set[str],
    canonicalize_path: bool = True,
) -> str:
    """
    Build a stable, rule-compliant HDF5 group name with hash suffix.

    The hash prevents accidental collisions after sanitization.
    """
    canonical = (
        normalize_source_name(original_name) if canonicalize_path else str(original_name)
    )
    safe = h5_safe_name(canonical)
    digest = hashlib.sha1(str(original_name).encode("utf-8")).hexdigest()[:8]
    candidate = f"{prefix}_{safe}_{digest}"
    return ensure_unique_name(candidate, used_names)


def make_cache_h5_key(source_name: str, prefix: str = "data") -> str:
    """
    Build a deterministic cache key from source name.

    Uses basename normalization so path variant differences do not create
    duplicate cache branches.
    """
    canonical = normalize_source_name(source_name)
    key = h5_safe_name(canonical)
    if key and key[0].isdigit():
        key = f"{prefix}_{key}"
    return key


def encode_attr_value(value: Any) -> Any:
    """Encode attr value into HDF5-friendly scalar/string."""
    if isinstance(value, np.generic):
        value = value.item()
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="ignore")
    if isinstance(value, (str, int, float, bool)):
        return value
    return "__json__" + json.dumps(value, ensure_ascii=False, default=str)


def decode_attr_value(value: Any) -> Any:
    """Decode attribute value produced by encode_attr_value."""
    if isinstance(value, bytes):
        value = value.decode("utf-8", errors="ignore")
    if isinstance(value, str) and value.startswith("__json__"):
        payload = value[len("__json__") :]
        try:
            return json.loads(payload)
        except Exception:
            return payload
    return value


def _safe_meta_part(part: str) -> str:
    """Normalize metadata key segments for attribute names."""
    text = h5_affixed_name(str(part))
    return text or "key"


def flatten_metadata_attrs(
    metadata: Mapping[str, Any],
) -> dict[str, Any]:
    """
    Flatten nested metadata dictionary into HDF5 attrs.

    Example:
        {"a": {"b": 1}} -> {"a__b": 1}
    """
    flat: dict[str, Any] = {}

    def _walk(parent_parts: list[str], value: Any) -> None:
        if isinstance(value, Mapping):
            for k, v in value.items():
                _walk(parent_parts + [_safe_meta_part(k)], v)
            return
        key = H5_META_SEP.join(parent_parts)
        flat[key] = encode_attr_value(value)

    for k, v in metadata.items():
        _walk([_safe_meta_part(k)], v)
    return flat


def unflatten_metadata_attrs(
    attrs: Mapping[str, Any],
) -> dict[str, Any]:
    """Reconstruct nested metadata dictionary from HDF5 attrs."""
    restored: dict[str, Any] = {}
    for raw_key, raw_value in attrs.items():
        key = str(raw_key)
        path = key.split(H5_META_SEP)
        cursor = restored
        for part in path[:-1]:
            if part not in cursor or not isinstance(cursor[part], dict):
                cursor[part] = {}
            cursor = cursor[part]
        cursor[path[-1]] = decode_attr_value(raw_value)
    return restored


# Backward-compat aliases for existing internal imports.
_h5_safe_name = h5_safe_name
_ensure_unique_name = ensure_unique_name
_decode_attr_value = decode_attr_value


__all__ = [
    "H5_GROUP_RAWDATA", "H5_GROUP_DENSITY", "H5_GROUP_STFT", "H5_GROUP_CWT", "H5_GROUP_VEST",
    "H5_META_SEP", "NATURAL_NAME_RE",
    "h5_safe_token", "h5_safe_name", "h5_affixed_name", "parse_h5_affixed_name",
    "ensure_unique_name", "normalize_source_name", "make_h5_group_name",
    "make_cache_h5_key",
    "encode_attr_value", "decode_attr_value",
    "flatten_metadata_attrs", "unflatten_metadata_attrs",
]
