#!/usr/bin/env python3
"""
Signal Utilities (Filter)
=========================

This module provides utilities for filtering signals.

Author: J. Wang
Date: 2025-01-16
"""

import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import freqz, remez

from ...plot import Plotter
from ...utils.log_manager import LogManager, log_tag
from .remezord import remezord

logger = LogManager().get_logger(__name__)

def create_lpf(
    f_pass: float, f_stop: float, fs: float, approx: bool = False, max_taps: int | None = None) -> np.ndarray:
    r"""
    Create a low-pass FIR filter using the remez (Parks-McClellan) algorithm.

    An optimal FIR filter with specified passband and stopband frequencies. 
    The filter coefficients are generated by using remezord to 
    determine the optimal number of taps and remez to generate the filter coefficients.

    Args:
        approx (bool, optional): Whether to use approximate tap count instead of remezord.
            If True, uses rule-of-thumb: $N \approx 4 / (transition_width_normalized)$.
        max_taps (int, optional): Maximum number of filter taps to prevent filtfilt issues
            with short signals. If None, no limit is applied.

    Returns:
        np.ndarray: FIR filter coefficients (taps) for use with :func:`scipy.signal.filtfilt`.

    Notes:
        - Filter specifications: ~0.5 dB passband ripple, -80 dB stopband attenuation.
        - The number of taps is always odd (required by remez).
        - Filter coefficients are designed for use with filtfilt (zero-phase filtering).
        - Frequency order must be: f_pass < f_stop < Nyquist frequency.

    Examples:
        ```python
        lpf_taps = create_lpf(f_pass=0.5e6, f_stop=1e6, fs=50e6)
        # Apply filter
        from scipy.signal import filtfilt
        filtered_signal = filtfilt(lpf_taps, 1, signal)
        ```
    """
    nyq = 0.5 * fs
    # dens from matlab is 20, which is the weight.
    # The transition width is f_stop - f_pass.
    # Let's assume a reasonable ripple.
    # Dpass = 0.0575, Dstop = 0.0001 from LPF.m
    # This translates to about 0.5 dB ripple in passband and -80 dB attenuation in stopband.
    # numtaps, bands, desired, weight = remezord([f_pass, f_stop], [1, 0], [0.0575, 0.0001], Hz=fs)
    # remezord is not in scipy, so we have to estimate the number of taps.
    # A common rule of thumb: N = 4 / (transition_width_normalized)
    numtaps_approx = int(4 / ((f_stop - f_pass) / nyq))
    if numtaps_approx % 2 == 0:
        numtaps_approx += 1

    freqs = [f_pass, f_stop]
    amps = [1, 0]
    rip_pass = 0.057501127785  # pass-band ripple (linear)
    rip_stop = 1e-4  # stop-band ripple (linear)
    rips = [rip_pass, rip_stop]

    [numtaps, bands, amps, weight] = remezord(
        freqs, amps, rips, Hz=fs, alg="herrmann"
    )

    # Limit the number of taps to prevent filtfilt issues
    if max_taps is not None:
        numtaps = min(numtaps, max_taps)
        if numtaps % 2 == 0:
            numtaps += 1

    # compare the numtaps from remezord and approximate one
    if abs(numtaps - numtaps_approx) > 50 and not approx:  # Allow some tolerance
        logger.info(
            f"{log_tag('PHI2N', 'LPF')} numtaps from remezord: {numtaps}, numtaps_approx: {numtaps_approx}"
        )
        logger.info(
            f"{log_tag('PHI2N', 'LPF')} Difference is significant. Using the value from remezord."
        )
        pass
    elif approx:
        logger.info(
            f"{log_tag('PHI2N', 'LPF')} Using approximate numtaps: {numtaps_approx}"
        )
        numtaps = numtaps_approx
    if all(bands) <= 1.0:
        taps = remez(numtaps=numtaps, bands=bands, desired=amps, weight=weight, fs=1.0, grid_density=20)
    else:
        taps = remez(numtaps=numtaps, bands=bands, desired=amps, weight=weight, fs=fs, grid_density=20)

    return taps

def create_hpf(
    f_stop: float, f_pass: float, fs: float, approx: bool = False, max_taps: int | None = None) -> np.ndarray:
    r"""
    Create a high-pass FIR filter using the remez (Parks-McClellan) algorithm.

    An optimal FIR filter with specified passband and stopband frequencies. 
    The filter coefficients are generated by using remezord to 
    determine the optimal number of taps and remez to generate the filter coefficients.

    Args:
        approx (bool, optional): Whether to use approximate tap count instead of remezord.
            If True, uses rule-of-thumb: $N \approx 4 / (transition_width_normalized)$.
        max_taps (int, optional): Maximum number of filter taps to prevent filtfilt issues
            with short signals. If None, no limit is applied.

    Returns:
        np.ndarray: FIR filter coefficients (taps) for use with :func:`scipy.signal.filtfilt`.

    Notes:
        - Filter specifications: ~0.5 dB passband ripple, -80 dB stopband attenuation.
        - The number of taps is always odd (required by remez).
        - Filter coefficients are designed for use with filtfilt (zero-phase filtering).
        - Frequency order must be: f_stop < f_pass < Nyquist frequency.
    """
    nyq = 0.5 * fs
    
    # Validate frequency order
    if f_stop >= f_pass:
        raise ValueError(
            f"Highpass filter requires f_stop < f_pass. Got f_stop={f_stop} Hz, f_pass={f_pass} Hz"
        )
    if f_pass >= nyq:
        raise ValueError(
            f"Passband frequency must be below Nyquist frequency. Got f_pass={f_pass} Hz, Nyquist={nyq} Hz"
        )
    
    # Transition width is f_pass - f_stop
    # A common rule of thumb: N = 4 / (transition_width_normalized)
    numtaps_approx = int(4 / ((f_pass - f_stop) / nyq))
    if numtaps_approx % 2 == 0:
        numtaps_approx += 1

    freqs = [f_stop, f_pass]
    amps = [0, 1]  # Stopband at 0, passband at 1 (opposite of LPF)
    rip_stop = 1e-4  # stop-band ripple (linear)
    rip_pass = 0.057501127785  # pass-band ripple (linear)
    rips = [rip_stop, rip_pass]  # Order: stopband ripple first, then passband ripple

    [numtaps, bands, amps, weight] = remezord(
        freqs, amps, rips, Hz=fs, alg="herrmann"
    )

    # Limit the number of taps to prevent filtfilt issues
    if max_taps is not None:
        numtaps = min(numtaps, max_taps)
        if numtaps % 2 == 0:
            numtaps += 1

    # compare the numtaps from remezord and approximate one
    if abs(numtaps - numtaps_approx) > 50 and not approx:  # Allow some tolerance
        logger.info(
            f"{log_tag('PHI2N', 'HPF')} numtaps from remezord: {numtaps}, numtaps_approx: {numtaps_approx}"
        )
        logger.info(
            f"{log_tag('PHI2N', 'HPF')} Difference is significant. Using the value from remezord."
        )
        pass
    elif approx:
        logger.info(
            f"{log_tag('PHI2N', 'HPF')} Using approximate numtaps: {numtaps_approx}"
        )
        numtaps = numtaps_approx
    
    if all(bands) <= 1.0:
        taps = remez(numtaps=numtaps, bands=bands, desired=amps, weight=weight, fs=1.0, grid_density=20)
    else:
        taps = remez(numtaps=numtaps, bands=bands, desired=amps, weight=weight, fs=fs, grid_density=20)

    return taps

def create_bpf(
    f_stop1: float, f_pass1: float, f_pass2: float, f_stop2: float, fs: float, approx: bool = False) -> np.ndarray:
    r"""
    Create a band-pass FIR filter using the remez (Parks-McClellan) algorithm.

    An optimal FIR band-pass filter with specified stopbands and passbands frequencies. 
    The filter coefficients are generated by using remezord to 
    determine the optimal number of taps and remez to generate the filter coefficients.

    Args:
        approx (bool, optional): Whether to use approximate tap count instead of remezord.
            If True, uses rule-of-thumb: $N \approx 4 / (transition_width_normalized)$.

    Returns:
        np.ndarray: FIR filter coefficients (taps) for use with :func:`scipy.signal.filtfilt`.

    Notes:
        - Filter specifications: ~0.5 dB passband ripple, -80 dB stopband attenuation.
        - The number of taps is always odd (required by remez).
        - Filter coefficients are designed for use with filtfilt (zero-phase filtering).
        - Frequency order must be: f_stop1 < f_pass1 < f_pass2 < f_stop2.
    """
    nyq = 0.5 * fs
    numtaps_approx = int(4 / ((f_pass1 - f_stop1) / nyq))  # estimate from one side
    if numtaps_approx % 2 == 0:
        numtaps_approx += 1

    freqs = [f_stop1, f_pass1, f_pass2, f_stop2]
    amps = [0, 1, 0]
    rip_stop1 = 1e-4  # stop-band ripple (linear)
    rip_pass = 0.057501127785  # pass-band ripple (linear)
    rip_stop2 = 1e-4  # stop-band ripple (linear)
    rips = [rip_stop1, rip_pass, rip_stop2]

    [numtaps, bands, amps, weight] = remezord(
        freqs, amps, rips, Hz=fs, alg="herrmann"
    )

    # compare the numtaps from remezord and approximate one
    if abs(numtaps - numtaps_approx) > 50 and not approx:  # Allow some tolerance
        logger.info(
            f"{log_tag('PHI2N', 'BPF')} numtaps from remezord: {numtaps}, numtaps_approx: {numtaps_approx}"
        )
        logger.info(
            f"{log_tag('PHI2N', 'BPF')} Difference is significant. Using the value from remezord."
        )
        pass
    elif approx:
        logger.info(
            f"{log_tag('PHI2N', 'BPF')} Using approximate numtaps: {numtaps_approx}"
        )
        numtaps = numtaps_approx

    if all(bands) <= 1.0:
        taps = remez(numtaps=numtaps, bands=bands, desired=amps, weight=weight, fs=1.0, grid_density=20)
    else:
        taps = remez(numtaps=numtaps, bands=bands, desired=amps, weight=weight, fs=fs, grid_density=20)

    return taps

def plot_filter_response(
    taps: np.ndarray,
    fs: float | None = None,
    title: str = "Frequency Response",
) -> None:
    r"""
    Plot the frequency response of an FIR filter.

    Args:
    fs(float | None): Sampling frequency [Hz]. If None, uses 2$\pi$
    """
    if fs is None:
        fs = 2 * np.pi
        logger.warning(
            f"{log_tag('PHI2N', 'VFILT')} fs is not provided, using 2*pi, resulting in frequency in rad/sample"
        )
    freqs_at_response, responses = freqz(taps, worN=2048, fs=fs)
    Plotter().plot_response(freqs_at_response, responses, title)
    plt.show()


